---
name: Feedback
version: 1.0.0
main: AmitxD\Feedback\Main
src-namespace-prefix: AmitxD\Feedback
api: 4.12.8
author: AmitxD
website: https://github.com/Amitminer888/Feedback
commands:
 feedback:
  description: just another useless plugin
  usage: "/feedback <msg>"
  permission: Feedback.command.feedback
permissions:
  Feedback.command.feedback:
    description: "Allows the user to run the example command"
    default: true
...
